# Site settings
title: Integrate
email: b@benWoz.com
description: "Tools & Experiences gleaned from living with Vision, Integrity & Purpose."
baseurl: ""
url: "http://benWoz.com"
twitter_username: benWoz
github_username:  benWoz

# Build settings
markdown: kramdown
permalink: pretty
